name: Build & Publish Images to GHCR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'images/**'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

concurrency:
  group: ghcr-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          # Add more images by appending items to this matrix
          - name: node-dev
            context: images/node
            # Rolling tag you want consumers to pull by default
            rolling_tag: 22-alpine
            # Build args passed to Dockerfile in this context
            build_args: |
              NODE_VERSION=22-alpine

          - name: php-dev
            context: images/php
            rolling_tag: 8.1-fpm
            build_args: |
              PHP_VERSION=8.1.5-fpm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          DATE_TAG=$(date +%Y%m%d)
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT
          SHORT_SHA=${GITHUB_SHA::7}
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build & push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: ${{ matrix.build_args }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ matrix.rolling_tag }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.meta.outputs.date_tag }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ steps.meta.outputs.short_sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.run_created_at }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
